<?xml version="1.0" encoding="utf-8"?><Database Name="ShopBanNickGame" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="MaCT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Matkhau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MaDH" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="MaDH" OtherKey="MaDH" Type="DonHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="MaDM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="DanhMuc_DanhMucCT" Member="DanhMucCTs" ThisKey="MaDM" OtherKey="MaDM" Type="DanhMucCT" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucCT" Member="DanhMucCTs">
    <Type Name="DanhMucCT">
      <Column Name="MaCTDanhMuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MaDM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DanhMucCT_NickLM" Member="NickLMs" ThisKey="MaCTDanhMuc" OtherKey="MaCTDanhMuc" Type="NickLM" />
      <Association Name="DanhMuc_DanhMucCT" Member="DanhMuc" ThisKey="MaDM" OtherKey="MaDM" Type="DanhMuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="ThoiGianMua" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaTien" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="MaNick" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDH" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaDH" OtherKey="MaDH" Type="ChiTietDonHang" />
      <Association Name="NickLM_DonHang" Member="NickLM" ThisKey="MaNick" OtherKey="MaNick" Type="NickLM" IsForeignKey="true" />
      <Association Name="NguoiDung_DonHang" Member="NguoiDung" ThisKey="MaKH" OtherKey="MaKH" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NickLM" Member="NickLMs">
    <Type Name="NickLM">
      <Column Name="MaNick" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Rank" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangPhuc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MaCTDanhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ThuVienChuaHinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NickLM_DonHang" Member="DonHangs" ThisKey="MaNick" OtherKey="MaNick" Type="DonHang" />
      <Association Name="DanhMucCT_NickLM" Member="DanhMucCT" ThisKey="MaCTDanhMuc" OtherKey="MaCTDanhMuc" Type="DanhMucCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Tendangnhap" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="chucvu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NguoiDung_DonHang" Member="DonHangs" ThisKey="MaKH" OtherKey="MaKH" Type="DonHang" />
    </Type>
  </Table>
</Database>